apiVersion: v1
kind: Pod
metadata:
  name: Pod1
  labels:
    app: web
spec:
  containers:
    - name: container1
      image: nginx
      ports:
        - containerPort: 30010
    - name: container2
      image: nginx
      ports:
        - containerPort: 30010
    - name: container3
      image: nginx
      ports:
        - containerPort: 30010